default:
	-rm meshgen.{aux,bbl,blg}
	pdflatex meshgen.tex
	bibtex meshgen
	pdflatex meshgen.tex
	pdflatex meshgen.tex
	zip arxiv_export.zip meshgen.tex meshgen.bbl esimerkki_1.png esimerkki_2.png esimerkki_3.png esimerkki_4.png siamplain.bst image_19.png image_5.png image_5.png image_6.png image_6.png image_7.png image_19.png image_5.png image_6.png image_7.png image_8.png image_9.png image_10.png image_11.png image_12.png image_13.png image_14.png image_15.png image_16.png image_17.png image_1.png image_2.png image_4.png image_21.png image_23.png
